### ISSUE TITLE
Uncompressed kdbx causes loadFile not to call it's callback

### ISSUE THREAD

**Issue by gustavnikolaj** [NeoXiD/keepass.io#14]
I created a test file from keepass2 and used that for some tests. I turned off gzipping as I thought it would just complicate things.

When trying to call kpio.loadFile on that file, it never calls it's callback - and it doesn't even throw an error.

The CompressionFlags field in the Header is 0x01 0x00 0x00 0x00 if the file is gzipped and 0x00 0x00 0x00 0x00 if it's not.

**Comment by NeoXiD** [comment]
Thanks for your bug report. I've just confirmed that issue and am going to release a hotfix within the next few hours.

**Comment by NeoXiD** [comment]
This issue should be now resolved in version 1.1.1, both loading and saving of non-gzipped databases wasn't properly implemented. Sorry for that, if any further problems should occur, please tell me so.

**Comment by gustavnikolaj** [comment]
Looks great! I'll let you know if I run into any oddities :-) Happy new year!

**Comment by NeoXiD** [comment]
Thanks, happy new year too! :)
